### ISSUE TITLE
Track cash transfers as asset transaction type

### ISSUE THREAD

**Issue by filo87** [centrifuge/pools-subql#134]
**Extend AssetTransactionType**
```graphql
enum AssetTransactionType {
  CREATED
  BORROWED
  REPAID
  CLOSED
  CASH_DEPOSIT
  CASH_WITHDRAWAL
  CASH_TRANSFER // to/from onchain reserve 
}
```

**Create `OnchainCash` asset**
When pool is created, create an asset by default with type = `OnchainCash`.

**If there is a transfer debt from a non-cash asset to an `OffchainCash` asset**
- Track repayment amount
- Create `PrincipalRepayment` transaction for the non-cash asset, with `fromAsset = OffchainCash asset` and `amount = repaidAmount`
- Create `CashDeposit` transaction type for the cash asset, with `toAsset = non-cash asset` and `amount = borrowAmount`

=> this will show up as a principal repayment in the Cashflows chart

**If there is a transfer debt from an `OffchainCash` asset to non-cash asset**
- Track borrowed/financed amount
- Create `Purchase` transaction for the non-cash asset, with `fromAsset = OffchainCash asset` and `amount = borrowAmount`
- Create `CashWithdrawal` transaction for the cash asset, with `toAsset = non-cash asset` and `amount = repaidAmount`

=> this will show up as a purchase in the Cashflows chart

**If there is a purchase of an `OffchainCash` asset**
- Don't track any financing/repayment amounts
- Create a `CashTransfer` transaction for the cash asset, with `fromAsset = OnchainCash asset`

=> this won't show up in the Cashflows chart

**If there is a repayment of an `OffchainCash` asset**
- Don't track any financing/repayment amounts
- Create a `CashTransfer` transaction for the cash asset, with `toAsset = OnchainCash asset`

=> this won't show up in the Cashflows chart

**Comment by hieronx** [comment]
@filo87 updated the description above.

> the purchase CashTransfer ?
> the repaid CashTransfer ?

These are not based on transfer debt events (just normal Borrow/Repaid events of the cash asset)
