### ISSUE TITLE
Investigate missing pool fee snapshots

### ISSUE THREAD

**Issue by hieronx** [centrifuge/pools-subql#202]
When querying poolsnapshots and poolfeesnapshots from Jan 1 2024, the number of elements is not matching:

![Screenshot 2024-06-13 at 10 16 23](https://github.com/centrifuge/pools-subql/assets/1748621/706e6f5e-350a-4a48-924f-83cefcb6b81b)

**Comment by sophialittlejohn** [comment]
This was a query for the Anemoy, turns out that the fee snapshots don't start until the fees were added to the pool which in this case was around March 28th. Closing the issue.
