### ISSUE TITLE
Migration to Liquidity Pools v2

### ISSUE THREAD

**Issue by hieronx** [centrifuge/pools-subql#230]
New pool managers:
- Ethereum: `0x91808B5E2F6d7483D41A681034D7c9DbB64B9E29`
- Base: `0x7f192F34499DdB2bE06c4754CFf2a21c4B056994`
- Celo: `0xa3Ce97352C1469884EEF3547Ec9362329FE78Cf0`
- Arbitrum: `0x91808B5E2F6d7483D41A681034D7c9DbB64B9E29`

Migration transaction (example): https://etherscan.io/tx/0x0209afaef6f4816ba268e04f430106817402ca3713ca5bf28fccaa778e84d5fb

Migrated on Aug 7th

**Comment by filo87** [comment]
@hieronx Here shall we just add the new pool managers to the indexer and these will listen to the new DeployTrancheToken events and therefore attach the new ERC-20 listeners, or did something change there in the implementation of the PoolManager?

**Comment by hieronx** [comment]
@filo87 the ABI slightly changed I'm afraid. Here is the v2 version:

[PoolManagerV2.abi.json](https://github.com/user-attachments/files/16596373/PoolManagerV2.abi.json)

**Comment by filo87** [comment]
@hieronx is there a new contract also for sepolia?

**Comment by hieronx** [comment]
My bad, forgot this in the list of the changes.

There is actually no router escrow anymore.

For the escrow, in most cases this should be the same across chains, but we can't always guarantee it.  Here's the list:
-  Ethereum, Arbitrum, Base: `0x0000000005F458Fd6ba9EEb5f365D83b7dA913dD`
- Celo: `0x9EDf9FC14DDBEE68CE1a69827b09794367180717`

**Comment by hieronx** [comment]
Just additional context: all addresses can always be found in https://github.com/centrifuge/liquidity-pools/tree/main/deployments
